FROM clojure:lein-alpine
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY project.clj /usr/src/app/
RUN lein deps
COPY . /usr/src/app
RUN lein uberjar
RUN mv target/homepage.jar ./app-standalone.jar
EXPOSE 3000
CMD ["java", "-jar", "app-standalone.jar"]
