POST http://localhost:3449/send-message
Content-Type: application/json
g-recaptcha-response: stub

{
  "firstname": "Rory",
  "lastname": "How",
  "email": "rhow93@gmail.com",
  "message": "Hello there, Rory!"
}