#
#
#
GET http://localhost:3449/my-ip
api-key: 3add7cf8-c416-4d99-abdb-80a25e1a49d3


#
#
#
POST http://localhost:3449/send-message
Content-Type: application/json
g-recaptcha-response: stub
api-key: 3add7cf8-c416-4d99-abdb-80a25e1a49d3

{
  "firstname": "Rory",
  "lastname": "How",
  "email": "rhow93@gmail.com",
  "message": "Hello there, Rory!"
}

#
#
#
POST http://roryhow.com/send-message
Content-Type: application/json
g-recaptcha-response: stub
api-key: 8d430279-fd0b-423a-8d39-f08c49faebfb

{
  "firstname": "Rory",
  "lastname": "How",
  "email": "rhow93@gmail.com",
  "message": "Hello there, Rory!"
}